"""
Django settings for alx_backend_security project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-$^0-)ypj&^3*3nygd9qgh3f7m$h+-8efm!i7&p_&-w+a3s8@we"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition
INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ip_tracking",
    "ipware",
    "user_agents",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ip_tracking.middleware.IPLoggingMiddleware",
]

USER_AGENT_CACHE = "default"

IP_META_PRECEDENCE_ORDER = [
    "HTTP_X_FORWARDED_FOR",
    "HTTP_X_REAL_IP",
    "REMOTE_ADDR",
]

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
        'ip_tracking_file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'ip_tracking.log',
        },
        'ratelimit_file': {
            'level': 'WARNING',
            'class': 'logging.FileHandler',
            'filename': 'ratelimit.log',
        },
    },
    'loggers': {
        'ip_tracking': {
            'handlers': ['ip_tracking_file'],
            'level': 'INFO',
            'propagate': True,
        },
        'django_ratelimit': {
            'handlers': ['console', 'ratelimit_file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = "alx_backend_security.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "alx_backend_security.wsgi.application"

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/
LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/
STATIC_URL = "static/"

# Rate Limiting Configuration
RATELIMIT_ENABLE = True
RATELIMIT_USE_CACHE = 'default'
RATELIMIT_FAIL_OPEN = False

RATELIMIT_CONFIG = {
    'DEFAULT': {
        'LIMIT': '100/hour',
        'METHOD': 'GET|POST|PUT|PATCH|DELETE',
        'GROUP': 'default',
    },
    'AUTHENTICATED': {
        'LIMIT': '10/minute',
        'METHOD': 'GET|POST|PUT|PATCH|DELETE',
        'GROUP': 'authenticated',
    },
    'ANONYMOUS': {
        'LIMIT': '5/minute',
        'METHOD': 'GET|POST|PUT|PATCH|DELETE',
        'GROUP': 'anonymous',
    },
    'SENSITIVE': {
        'LOGIN': '3/minute',
        'REGISTER': '2/minute',
        'PASSWORD_RESET': '2/minute',
        'GROUP': 'sensitive',
    },
    'API': {
        'DEFAULT': '60/hour',
        'BURST': '10/minute',
        'GROUP': 'api',
    },
}

RATELIMIT_KEY_PREFIX = 'ratelimit'
RATELIMIT_VIEW = 'ip_tracking.views.rate_limit_exceeded'
RATELIMIT_MODEL = 'ip_tracking.RateLimit'

# IP blocking configuration
IP_BLOCKING = {
    'ENABLED': True,
    'MAX_ATTEMPTS': 10,
    'BLOCK_DURATION': 3600,
    'PERMANENT_BLOCK_AFTER': 50,
}

SECURE_RATE_LIMITING = {
    'ENABLE_X_RATELIMIT_HEADERS': True,
    'X_RATELIMIT_LIMIT': 'X-RateLimit-Limit',
    'X_RATELIMIT_REMAINING': 'X-RateLimit-Remaining',
    'X_RATELIMIT_RESET': 'X-RateLimit-Reset',
}

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

# Anomaly detection configuration
ANOMALY_DETECTION = {
    'ENABLED': True,
    'CHECK_INTERVAL_HOURS': 1,
    'REQUEST_THRESHOLD': 100,
    'SENSITIVE_PATHS': [
        '/admin/', '/admin', '/login/', '/login', '/register/', '/register',
        '/password-reset/', '/password-reset', '/api/', '/dashboard/',
        '/dashboard', '/profile/', '/profile', '/settings/', '/settings',
    ],
    'HIGH_RISK_PATHS': ['/admin/', '/admin', '/password-reset/', '/password-reset'],
    'USER_AGENT_PATTERNS': [
        'sqlmap', 'nikto', 'nmap', 'nessus', 'metasploit', 'burpsuite',
        'dirbuster', 'wpscan', 'hydra', 'john', 'havij', 'acunetix',
        'appscan', 'zap', 'skipfish', 'w3af',
    ],
    'SUSPICIOUS_COUNTRIES': ['CN', 'RU', 'KP', 'IR', 'SY'],
    'MIN_REQUESTS_FOR_ANALYSIS': 5,
    'CONFIDENCE_THRESHOLD': 0.7,
}

