# Generated by Django 6.0 on 2026-01-12 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("path", models.CharField(max_length=500)),
                ("method", models.CharField(max_length=10)),
                ("query_string", models.TextField(blank=True)),
                ("user_agent", models.TextField(blank=True)),
                ("is_mobile", models.BooleanField(default=False)),
                ("is_tablet", models.BooleanField(default=False)),
                ("is_touch_capable", models.BooleanField(default=False)),
                ("is_pc", models.BooleanField(default=False)),
                ("is_bot", models.BooleanField(default=False)),
                ("browser", models.CharField(blank=True, max_length=200)),
                ("browser_version", models.CharField(blank=True, max_length=50)),
                ("os", models.CharField(blank=True, max_length=100)),
                ("os_version", models.CharField(blank=True, max_length=50)),
                ("device", models.CharField(blank=True, max_length=200)),
                ("status_code", models.IntegerField(blank=True, null=True)),
                ("response_size", models.IntegerField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "response_time",
                    models.FloatField(
                        blank=True, help_text="Response time in seconds", null=True
                    ),
                ),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("region", models.CharField(blank=True, max_length=100)),
                ("referer", models.URLField(blank=True)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="request_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Request Log",
                "verbose_name_plural": "Request Logs",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["ip_address"], name="ip_tracking_ip_addr_3489f7_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="ip_tracking_timesta_b1bb90_idx"
                    ),
                    models.Index(fields=["path"], name="ip_tracking_path_65894f_idx"),
                    models.Index(
                        fields=["user"], name="ip_tracking_user_id_fad2f0_idx"
                    ),
                    models.Index(
                        fields=["status_code"], name="ip_tracking_status__67a937_idx"
                    ),
                ],
            },
        ),
    ]
