# Generated by Django 5.2.10 on 2026-01-24 13:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ip_tracking', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomalyDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('detection_type', models.CharField(max_length=50)),
                ('severity', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('details', models.JSONField(default=dict)),
                ('triggered_rules', models.JSONField(default=list)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='BlockedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True, verbose_name='IP Address')),
                ('subnet_mask', models.PositiveIntegerField(blank=True, default=32, help_text='Subnet mask (8-32 for IPv4, 128 for IPv6)', null=True)),
                ('block_type', models.CharField(choices=[('permanent', 'Permanent Block'), ('temporary', 'Temporary Block'), ('rate_limit', 'Rate Limit Block'), ('manual', 'Manual Block'), ('suspicious', 'Suspicious Activity'), ('abuse', 'Abuse/Misuse'), ('spam', 'Spam'), ('scanner', 'Security Scanner'), ('bot', 'Malicious Bot'), ('vpn_proxy', 'VPN/Proxy'), ('tor', 'TOR Network'), ('country', 'Country Block'), ('asn', 'ASN Block')], default='manual', max_length=20, verbose_name='Block Type')),
                ('is_permanent', models.BooleanField(default=False, verbose_name='Permanent Block')),
                ('block_duration', models.IntegerField(default=86400, help_text='Block duration in seconds (only for temporary blocks)', verbose_name='Block Duration')),
                ('blocked_at', models.DateTimeField(auto_now_add=True, verbose_name='Blocked At')),
                ('blocked_until', models.DateTimeField(blank=True, null=True, verbose_name='Blocked Until')),
                ('reason', models.TextField(help_text='Reason for blocking this IP', verbose_name='Block Reason')),
                ('source', models.CharField(default='manual', help_text='Source of block (manual, automated, threat_intel, etc.)', max_length=100, verbose_name='Block Source')),
                ('evidence', models.JSONField(blank=True, default=dict, help_text='Evidence or data supporting the block', verbose_name='Block Evidence')),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests from this IP before blocking', verbose_name='Request Count')),
                ('user_agents', models.JSONField(blank=True, default=list, help_text='User agents used by this IP', verbose_name='User Agents')),
                ('accessed_paths', models.JSONField(blank=True, default=list, help_text='Paths accessed by this IP', verbose_name='Accessed Paths')),
                ('country', models.CharField(blank=True, max_length=100, null=True, verbose_name='Country')),
                ('country_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Country Code')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('isp', models.CharField(blank=True, max_length=200, null=True, verbose_name='ISP')),
                ('threat_score', models.IntegerField(default=0, help_text='Threat score (0-100)', verbose_name='Threat Score')),
                ('known_malicious', models.BooleanField(default=False, verbose_name='Known Malicious')),
                ('spamhaus_listed', models.BooleanField(default=False, verbose_name='Spamhaus Listed')),
                ('tor_exit_node', models.BooleanField(default=False, verbose_name='TOR Exit Node')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Blocked IP',
                'verbose_name_plural': 'Blocked IPs',
                'ordering': ['-blocked_at'],
            },
        ),
        migrations.CreateModel(
            name='RateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('key', models.CharField(db_index=True, max_length=200)),
                ('count', models.IntegerField(default=0)),
                ('period', models.IntegerField(help_text='Period in seconds')),
                ('limit', models.IntegerField(help_text='Maximum allowed requests')),
                ('is_blocked', models.BooleanField(default=False)),
                ('blocked_at', models.DateTimeField(blank=True, null=True)),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('block_reason', models.TextField(blank=True, null=True)),
                ('violation_count', models.IntegerField(default=0)),
                ('last_violation', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SuspiciousIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True, unique=True)),
                ('reason', models.CharField(choices=[('high_request_rate', 'High Request Rate'), ('sensitive_path_access', 'Sensitive Path Access'), ('multiple_failed_logins', 'Multiple Failed Logins'), ('scanner_detected', 'Security Scanner Detected'), ('suspicious_country', 'Suspicious Country'), ('vpn_proxy_detected', 'VPN/Proxy Detected'), ('tor_network', 'TOR Network'), ('brute_force_attempt', 'Brute Force Attempt'), ('sql_injection_pattern', 'SQL Injection Pattern'), ('xss_attempt', 'XSS Attempt'), ('dos_attempt', 'Denial of Service Attempt'), ('credential_stuffing', 'Credential Stuffing'), ('api_abuse', 'API Abuse'), ('data_scraping', 'Data Scraping'), ('malicious_bot', 'Malicious Bot'), ('unknown', 'Unknown')], max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('investigating', 'Under Investigation'), ('false_positive', 'False Positive'), ('resolved', 'Resolved'), ('whitelisted', 'Whitelisted'), ('blacklisted', 'Blacklisted')], default='active', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0, help_text='0.0 to 1.0')),
                ('detection_method', models.CharField(blank=True, max_length=100, null=True)),
                ('first_detected', models.DateTimeField(auto_now_add=True)),
                ('last_detected', models.DateTimeField(auto_now=True)),
                ('request_count', models.IntegerField(default=0, help_text='Number of requests from this IP')),
                ('user_agents', models.JSONField(blank=True, default=list, help_text='List of user agents used')),
                ('accessed_paths', models.JSONField(blank=True, default=list, help_text='Paths accessed by this IP')),
                ('countries', models.JSONField(blank=True, default=list, help_text='Countries associated with this IP')),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('isp', models.CharField(blank=True, max_length=200, null=True)),
                ('is_vpn', models.BooleanField(default=False)),
                ('is_proxy', models.BooleanField(default=False)),
                ('is_tor', models.BooleanField(default=False)),
                ('threat_intelligence', models.JSONField(blank=True, default=dict, help_text='External threat intelligence data')),
                ('known_malicious', models.BooleanField(default=False)),
                ('known_botnet', models.BooleanField(default=False)),
                ('spamhaus_listed', models.BooleanField(default=False)),
                ('investigation_notes', models.TextField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True, null=True)),
                ('auto_block', models.BooleanField(default=False)),
                ('block_duration', models.IntegerField(default=86400, help_text='Block duration in seconds')),
                ('blocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Suspicious IP',
                'verbose_name_plural': 'Suspicious IPs',
                'ordering': ['-first_detected'],
            },
        ),
        migrations.RemoveIndex(
            model_name='requestlog',
            name='ip_tracking_ip_addr_3489f7_idx',
        ),
        migrations.RemoveIndex(
            model_name='requestlog',
            name='ip_tracking_timesta_b1bb90_idx',
        ),
        migrations.RemoveIndex(
            model_name='requestlog',
            name='ip_tracking_path_65894f_idx',
        ),
        migrations.RemoveIndex(
            model_name='requestlog',
            name='ip_tracking_user_id_fad2f0_idx',
        ),
        migrations.RemoveIndex(
            model_name='requestlog',
            name='ip_tracking_status__67a937_idx',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='is_bot',
            new_name='is_hosting',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='is_mobile',
            new_name='is_proxy',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='is_pc',
            new_name='is_tor',
        ),
        migrations.RenameField(
            model_name='requestlog',
            old_name='is_tablet',
            new_name='is_vpn',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='browser',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='device',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='is_touch_capable',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='os',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='os_version',
        ),
        migrations.RemoveField(
            model_name='requestlog',
            name='response_size',
        ),
        migrations.AddField(
            model_name='requestlog',
            name='asn',
            field=models.CharField(blank=True, help_text='Autonomous System Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='country_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='isp',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='organization',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='raw_geolocation_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='city',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='content_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='country',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='ip_address',
            field=models.GenericIPAddressField(db_index=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='path',
            field=models.CharField(db_index=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='query_string',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='referer',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='response_time',
            field=models.FloatField(default=0.0, help_text='Response time in seconds'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='status_code',
            field=models.IntegerField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='requestlog',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['country'], name='ip_tracking_country_d37b30_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['city'], name='ip_tracking_city_bcb1b9_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp', 'country'], name='ip_tracking_timesta_1b5975_idx'),
        ),
        migrations.AddIndex(
            model_name='requestlog',
            index=models.Index(fields=['timestamp', 'city'], name='ip_tracking_timesta_934412_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionlog',
            index=models.Index(fields=['ip_address', 'timestamp'], name='ip_tracking_ip_addr_072a10_idx'),
        ),
        migrations.AddIndex(
            model_name='anomalydetectionlog',
            index=models.Index(fields=['detection_type', 'timestamp'], name='ip_tracking_detecti_78752d_idx'),
        ),
        migrations.AddField(
            model_name='blockedip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blocked_ips', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AddField(
            model_name='ratelimit',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate_limits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='suspiciousip',
            name='investigator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investigated_ips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['ip_address', 'is_permanent'], name='ip_tracking_ip_addr_aa74e1_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['block_type', 'blocked_at'], name='ip_tracking_block_t_0e2de0_idx'),
        ),
        migrations.AddIndex(
            model_name='blockedip',
            index=models.Index(fields=['country', 'blocked_at'], name='ip_tracking_country_64dc04_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimit',
            index=models.Index(fields=['ip_address', 'is_blocked'], name='ip_tracking_ip_addr_dc1de2_idx'),
        ),
        migrations.AddIndex(
            model_name='ratelimit',
            index=models.Index(fields=['key', 'created_at'], name='ip_tracking_key_1d65e5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ratelimit',
            unique_together={('ip_address', 'key')},
        ),
        migrations.AddIndex(
            model_name='suspiciousip',
            index=models.Index(fields=['ip_address', 'status'], name='ip_tracking_ip_addr_3a1b2f_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousip',
            index=models.Index(fields=['severity', 'status'], name='ip_tracking_severit_24a613_idx'),
        ),
        migrations.AddIndex(
            model_name='suspiciousip',
            index=models.Index(fields=['first_detected', 'severity'], name='ip_tracking_first_d_9e9485_idx'),
        ),
    ]
