"""
Django settings for alx_backend_security project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

ALLOWED_HOSTS = ["192.168.1.232", "127.0.0.1", "localhost"
                 ]
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "ip_tracking.apps.IpTrackingConfig", 
    "ipware",
    "user_agents",
    "django_celery_results",
    "django_celery_beat",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "ip_tracking.middleware.IPTrackingMiddleware",
    "ip_tracking.middleware.IPBlockingMiddleware",
    "ip_tracking.middleware.IPLoggingMiddleware",
 ]


IP_BLOCKING_ENABLED = True

USER_AGENT_CACHE = "default"

IP_META_PRECEDENCE_ORDER = [
    "HTTP_X_FORWARDED_FOR",
    "HTTP_X_REAL_IP",
    "REMOTE_ADDR",
]

# Logging configuration for IP tracking
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django_ratelimit': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # Add other loggers as needed, e.g., 'django': {...}
    },
}

ROOT_URLCONF = "alx_backend_security.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "alx_backend_security.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"

# Rate Limiting Configuration
RATELIMIT_ENABLE = True  # Enable/disable rate limiting
RATELIMIT_USE_CACHE = 'default'  # Use default cache backend
RATELIMIT_FAIL_OPEN = False  # If True, allow requests when cache fails

# Rate limiting configuration
RATELIMIT_CONFIG = {
    # Global defaults
    'DEFAULT': {
        'LIMIT': '100/hour',  # Global fallback limit
        'METHOD': 'GET|POST|PUT|PATCH|DELETE',
        'GROUP': 'default',
    },
    
    # Authenticated users
    'AUTHENTICATED': {
        'LIMIT': '10/minute',  # 10 requests per minute
        'METHOD': 'GET|POST|PUT|PATCH|DELETE',
        'GROUP': 'authenticated',
    },
    
    # Anonymous users
    'ANONYMOUS': {
        'LIMIT': '5/minute',  # 5 requests per minute
        'METHOD': 'GET|POST|PUT|PATCH|DELETE',
        'GROUP': 'anonymous',
    },
    
    # Sensitive endpoints (login, registration, etc.)
    'SENSITIVE': {
        'LOGIN': '3/minute',  # 3 login attempts per minute
        'REGISTER': '2/minute',  # 2 registration attempts per minute
        'PASSWORD_RESET': '2/minute',  # 2 password reset attempts per minute
        'GROUP': 'sensitive',
    },
    
    # API endpoints
    'API': {
        'DEFAULT': '60/hour',  # 60 API calls per hour
        'BURST': '10/minute',  # 10 calls per minute burst
        'GROUP': 'api',
    },
}

# Cache key prefix for rate limiting
RATELIMIT_KEY_PREFIX = 'ratelimit'

# Rate limit view (custom view for rate limit exceeded)
RATELIMIT_VIEW = 'ip_tracking.views.rate_limit_exceeded'

# Rate limit model (for storing rate limit data in DB)
RATELIMIT_MODEL = 'ip_tracking.RateLimit'

# IP blocking configuration
IP_BLOCKING = {
    'ENABLED': True,
    'MAX_ATTEMPTS': 10,  # Max failed attempts before blocking
    'BLOCK_DURATION': 3600,  # Block for 1 hour (in seconds)
    'PERMANENT_BLOCK_AFTER': 50,  # Permanent block after 50 violations
}

# Security headers for rate limiting
SECURE_RATE_LIMITING = {
    'ENABLE_X_RATELIMIT_HEADERS': True,
    'X_RATELIMIT_LIMIT': 'X-RateLimit-Limit',
    'X_RATELIMIT_REMAINING': 'X-RateLimit-Remaining',
    'X_RATELIMIT_RESET': 'X-RateLimit-Reset',
}

# Logging configuration for rate limiting
LOGGING['loggers']['django_ratelimit'] = {
    'handlers': ['console', 'file'],
    'level': 'WARNING',
    'propagate': False,
}

# Celery Configuration
CELERY_BROKER_URL = 'redis://localhost:6379/0'
CELERY_RESULT_BACKEND = 'django-db'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes

# Anomaly detection configuration
ANOMALY_DETECTION = {
    'ENABLED': True,
    'CHECK_INTERVAL_HOURS': 1,  # Run every hour
    'REQUEST_THRESHOLD': 100,   # 100 requests per hour
    'SENSITIVE_PATHS': [
        '/admin/',
        '/admin',
        '/login/',
        '/login',
        '/register/',
        '/register',
        '/password-reset/',
        '/password-reset',
        '/api/',
        '/dashboard/',
        '/dashboard',
        '/profile/',
        '/profile',
        '/settings/',
        '/settings',
    ],
    'HIGH_RISK_PATHS': [
        '/admin/',
        '/admin',
        '/password-reset/',
        '/password-reset',
    ],
    'USER_AGENT_PATTERNS': [
        'sqlmap',          # SQL injection tool
        'nikto',           # Web server scanner
        'nmap',            # Network scanner
        'nessus',          # Vulnerability scanner
        'metasploit',      # Penetration testing framework
        'burpsuite',       # Web vulnerability scanner
        'dirbuster',       # Directory brute forcer
        'wpscan',          # WordPress vulnerability scanner
        'hydra',           # Password cracker
        'john',            # Password cracker
        'havij',           # SQL injection tool
        'acunetix',        # Web vulnerability scanner
        'appscan',         # Security testing tool
        'zap',             # OWASP ZAP proxy
        'skipfish',        # Web application security scanner
        'w3af',            # Web application attack framework
    ],
    'SUSPICIOUS_COUNTRIES': [
        'CN',  # China
        'RU',  # Russia
        'KP',  # North Korea
        'IR',  # Iran
        'SY',  # Syria
    ],
    'MIN_REQUESTS_FOR_ANALYSIS': 5,  # Minimum requests to analyze
    'CONFIDENCE_THRESHOLD': 0.7,     # Confidence threshold for flagging
}
